### ISSUE TITLE
EasyBuild boostrapping does not work with SL 6.3 environment-modules package 

### ISSUE THREAD

**Issue by pelacables** [hpcugent/easybuild#29]
Hello,

I'm trying to install EasyBuild follwoing the bootstrapping procedure (https://github.com/hpcugent/easybuild/wiki/Bootstrapping-EasyBuild) . As I'm the process of bootstrapping I can only provide my python version: Python 2.6.6.

I did install environment-modules package: environment-modules-3.2.7b-6.el6.x86_64 and did not configure anything:

MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
LOADEDMODULES=
MODULESHOME=/usr/share/Modules

I followed the instructions and the install failed with:

== 2014-06-27 13:00:56,498 bootstrap_eb.filetools INFO Command modulecmd found at /usr/bin/modulecmd
== 2014-06-27 13:00:56,498 bootstrap_eb.EnvironmentModulesC INFO Full path for module command is /usr/bin/modulecmd, so using it
== 2014-06-27 13:00:56,525 bootstrap_eb.EnvironmentModulesC INFO Found version 3.2.7
== 2014-06-27 13:00:56,562 bootstrap_eb.EnvironmentModulesC ERROR EasyBuild crashed with an error (at easybuild/tools/modules.py:514 in run_module): ModuleCmd_Purge.c(114):ERROR:107: 'MODULEPATH' not set

The I didi install modules from source following https://github.com/hpcugent/easybuild/wiki/Installing-environment-modules-without-root-permissions and EasyBuild was installed.

From dependencies (https://github.com/hpcugent/easybuild/wiki/Dependencies) it is said that the rpm from SL is valid:

environment-modules, version >= 3.2.6
An rpm for this is available in the RHEL and SL repositories. 

Am I missing any extra conf for the default SL package?

TIA,
Arnau
